app1/urls.py
from django.urls import path
from app1.views import *
app_name='tarak'# we can provide any name.But we easly understand perpose function name and this name should be same.
urlpatterns=[
    path('a1_first/',a1_first,name='a1_first'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='vishnu' # we can provide any name.But we easly understand perpose function name and this name should be same.
urlpatterns=[
    path('a2_one/',a2_one,name='a2_one')
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def a1_first(request):
    return render(request,'a1_first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def a2_one(request):
    return render(request,'a2_one.html')

templates/a1_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is specific urls of a1_first</h1>
        <h1><a href="{% url 'vishnu:a2_one' %}">This is urlmapping of a2_one</a></h1>
    </center>
</body>
</html>

templates/a2_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is specific urls mapping of a2_one</h1>
        <h1><a href="{% url 'tarak:a1_first' %}">This is mapping to a1_first</a></h1>
    </center>
</body>
</html>